### ISSUE TITLE
Cannot pass variables into GraphQL Query

### ISSUE THREAD

**Issue by pngo12** [pngo12/LetUsChoose#2]
In the Sever/Controllers/Index.js file, I'm trying to pass req.parms into GraphQL queries to dynamically query Yelp's API. Right now if I hardcode some params, for example, term: "taco" location: Irvine, then that will work. But when I pass in a string literal from req.params, GraphQL errors out.

**Comment by m1771vw** [comment]
There was an issue where you were not properly passing in variables when making a client request. 
Client can take in multiple parameters - the one in particular is a **variable** object.

`client.request(query, variables)`

By passing in an object, you are able to use it in your GraphQL query when you declare a query.

```
query queryName($var1: String, $var2: String) {
    search(term: $var1, location: $var2) {
...
}
```
Please reference PR #3 for the fix.

**Comment by pngo12** [comment]
@m1771vw That worked. Thank you very much, closing the issue now.
